language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - cd ../
  - git clone -b master https://github.com/jpcw/mr.bobby.git
  - cd mr.bobby
  - python setup.py install
  - cd ../
  - git clone -b master https://github.com/jpcw/bobbyplugins.jpcw.git
  - cd bobbyplugins.jpcw
  - python setup.py install
  - cd ../bobbytemplates.thd/
  - python setup.py develop
  - easy_install . bobbytemplates.thd[test]
script:
  - make test -k
after_success:
  - easy_install coveralls
  - coveralls
